development:
  mode: "sandbox"
  username: "salomon.omer_api1.gmail.com"
  password: "1380958401"
  signature: "AKTmX5eGgu-1LRjREME7XhqcjiogApo6JtEThvMLEWnr8onZK2lNc5-U"
  application_id: "APP-80W284485P519543T"

test:
  mode: "sandbox"
  username: "salomon.omer_api1.gmail.com"
  password: "1380958401"
  signature: "AKTmX5eGgu-1LRjREME7XhqcjiogApo6JtEThvMLEWnr8onZK2lNc5-U"
  application_id: "APP-80W284485P519543T"

production:
  mode: "sandbox"
  username: "salomon.omer_api1.gmail.com"
  password: "1380958401"
  signature: "AKTmX5eGgu-1LRjREME7XhqcjiogApo6JtEThvMLEWnr8onZK2lNc5-U"
  application_id: "APP-80W284485P519543T"