development:
  environment: "sandbox"
  username: "salomon.omer-facilitator_api1.gmail.com"
  password: "1380958401"
  signature: "AKTmX5eGgu-1LRjREME7XhqcjiogApo6JtEThvMLEWnr8onZK2lNc5-U"
  application_id: "APP-80W284485P519543T"

test:
  environment: "sandbox"
  username: "salomon.omer-facilitator_api1.gmail.com"
  password: "1380958401"
  signature: "AKTmX5eGgu-1LRjREME7XhqcjiogApo6JtEThvMLEWnr8onZK2lNc5-U"
  application_id: "APP-80W284485P519543T"

production:
  environment: "sandbox"
  username: <%= ENV['PAYPAL_SANDBOX_USERNAME'] %>
  password: <%= ENV['PAYPAL_SANDBOX_PASSWORD'] %>
  signature: <%= ENV['PAYPAL_SANDBOX_SIGNATURE'] %>
  application_id: <%= ENV['PAYPAL_SANDBOX_APPID'] %>
