development:
  environment: "sandbox"
  username: "salomon.omer_api1.gmail.com"
  password: "A2RDZ7UP6YAAVT5A"
  signature: "AKHBx3F15DqGBpv4bzGQQW3CZk77ADu0mFztIDlSsk-4axFzxRUvuBPj"
  application_id: "APP-80W284485P519543T"

test:
  environment: "sandbox"
  username: "salomon.omer_api1.gmail.com"
  password: "A2RDZ7UP6YAAVT5A"
  signature: "AKHBx3F15DqGBpv4bzGQQW3CZk77ADu0mFztIDlSsk-4axFzxRUvuBPj"
  application_id: "APP-80W284485P519543T"

production:
  environment: "production"
  username: "my_production_username"
  password: "my_production_password"
  signature: "my_production_signature"
  application_id: "my_production_app_id"