test: &default

  # Credentials for REST APIs
  client_id: AXCPJxDybcxcrLDRiCCG0D1Lj-e-DcGzB62ovdI4hljrj3vReQ3Uni5obpiV
  client_secret: EMTrkBCw15mK44SiW2SQmZXK_vCNI6uS_KR668mRzABHerbhZzZVwnMTWNZK

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: salomon.omer_api1.gmail.com
  password: A2RDZ7UP6YAAVT5A
  signature: AKHBx3F15DqGBpv4bzGQQW3CZk77ADu0mFztIDlSsk-4axFzxRUvuBPj
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: salomon.omer-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
